name: Plugin request
description: Request a new plugin
title: "[Plugin request] "
labels: ["plugin request"]
body:

  - type: textarea
    id: plugin
    attributes:
      label: Plugin idea
      description: Please describe the plugin you are requesting in detail
      placeholder: describe....
